// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package protos.order;

public final class Order {
  private Order() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:order.OrderMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string manufacturer = 1;</code>
     * @return Whether the manufacturer field is set.
     */
    boolean hasManufacturer();
    /**
     * <code>required string manufacturer = 1;</code>
     * @return The manufacturer.
     */
    java.lang.String getManufacturer();
    /**
     * <code>required string manufacturer = 1;</code>
     * @return The bytes for manufacturer.
     */
    com.google.protobuf.ByteString
        getManufacturerBytes();

    /**
     * <code>required string product = 2;</code>
     * @return Whether the product field is set.
     */
    boolean hasProduct();
    /**
     * <code>required string product = 2;</code>
     * @return The product.
     */
    java.lang.String getProduct();
    /**
     * <code>required string product = 2;</code>
     * @return The bytes for product.
     */
    com.google.protobuf.ByteString
        getProductBytes();

    /**
     * <code>required int32 quantity = 3;</code>
     * @return Whether the quantity field is set.
     */
    boolean hasQuantity();
    /**
     * <code>required int32 quantity = 3;</code>
     * @return The quantity.
     */
    int getQuantity();

    /**
     * <code>required int32 willing_price = 4;</code>
     * @return Whether the willingPrice field is set.
     */
    boolean hasWillingPrice();
    /**
     * <code>required int32 willing_price = 4;</code>
     * @return The willingPrice.
     */
    int getWillingPrice();
  }
  /**
   * Protobuf type {@code order.OrderMessage}
   */
  public  static final class OrderMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:order.OrderMessage)
      OrderMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrderMessage.newBuilder() to construct.
    private OrderMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderMessage() {
      manufacturer_ = "";
      product_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OrderMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              manufacturer_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              product_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              quantity_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              willingPrice_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.order.Order.internal_static_order_OrderMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.order.Order.internal_static_order_OrderMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.order.Order.OrderMessage.class, protos.order.Order.OrderMessage.Builder.class);
    }

    private int bitField0_;
    public static final int MANUFACTURER_FIELD_NUMBER = 1;
    private volatile java.lang.Object manufacturer_;
    /**
     * <code>required string manufacturer = 1;</code>
     * @return Whether the manufacturer field is set.
     */
    public boolean hasManufacturer() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string manufacturer = 1;</code>
     * @return The manufacturer.
     */
    public java.lang.String getManufacturer() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          manufacturer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string manufacturer = 1;</code>
     * @return The bytes for manufacturer.
     */
    public com.google.protobuf.ByteString
        getManufacturerBytes() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manufacturer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCT_FIELD_NUMBER = 2;
    private volatile java.lang.Object product_;
    /**
     * <code>required string product = 2;</code>
     * @return Whether the product field is set.
     */
    public boolean hasProduct() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string product = 2;</code>
     * @return The product.
     */
    public java.lang.String getProduct() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          product_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string product = 2;</code>
     * @return The bytes for product.
     */
    public com.google.protobuf.ByteString
        getProductBytes() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        product_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 3;
    private int quantity_;
    /**
     * <code>required int32 quantity = 3;</code>
     * @return Whether the quantity field is set.
     */
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 quantity = 3;</code>
     * @return The quantity.
     */
    public int getQuantity() {
      return quantity_;
    }

    public static final int WILLING_PRICE_FIELD_NUMBER = 4;
    private int willingPrice_;
    /**
     * <code>required int32 willing_price = 4;</code>
     * @return Whether the willingPrice field is set.
     */
    public boolean hasWillingPrice() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 willing_price = 4;</code>
     * @return The willingPrice.
     */
    public int getWillingPrice() {
      return willingPrice_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasManufacturer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProduct()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuantity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWillingPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, manufacturer_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, product_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, quantity_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, willingPrice_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, manufacturer_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, product_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, quantity_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, willingPrice_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.order.Order.OrderMessage)) {
        return super.equals(obj);
      }
      protos.order.Order.OrderMessage other = (protos.order.Order.OrderMessage) obj;

      if (hasManufacturer() != other.hasManufacturer()) return false;
      if (hasManufacturer()) {
        if (!getManufacturer()
            .equals(other.getManufacturer())) return false;
      }
      if (hasProduct() != other.hasProduct()) return false;
      if (hasProduct()) {
        if (!getProduct()
            .equals(other.getProduct())) return false;
      }
      if (hasQuantity() != other.hasQuantity()) return false;
      if (hasQuantity()) {
        if (getQuantity()
            != other.getQuantity()) return false;
      }
      if (hasWillingPrice() != other.hasWillingPrice()) return false;
      if (hasWillingPrice()) {
        if (getWillingPrice()
            != other.getWillingPrice()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasManufacturer()) {
        hash = (37 * hash) + MANUFACTURER_FIELD_NUMBER;
        hash = (53 * hash) + getManufacturer().hashCode();
      }
      if (hasProduct()) {
        hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
        hash = (53 * hash) + getProduct().hashCode();
      }
      if (hasQuantity()) {
        hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
        hash = (53 * hash) + getQuantity();
      }
      if (hasWillingPrice()) {
        hash = (37 * hash) + WILLING_PRICE_FIELD_NUMBER;
        hash = (53 * hash) + getWillingPrice();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.order.Order.OrderMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.order.Order.OrderMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.order.Order.OrderMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.order.Order.OrderMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.order.Order.OrderMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.order.Order.OrderMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.order.Order.OrderMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.order.Order.OrderMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.order.Order.OrderMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.order.Order.OrderMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.order.Order.OrderMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.order.Order.OrderMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.order.Order.OrderMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code order.OrderMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:order.OrderMessage)
        protos.order.Order.OrderMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.order.Order.internal_static_order_OrderMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.order.Order.internal_static_order_OrderMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.order.Order.OrderMessage.class, protos.order.Order.OrderMessage.Builder.class);
      }

      // Construct using protos.order.Order.OrderMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        manufacturer_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        product_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        quantity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        willingPrice_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.order.Order.internal_static_order_OrderMessage_descriptor;
      }

      @java.lang.Override
      public protos.order.Order.OrderMessage getDefaultInstanceForType() {
        return protos.order.Order.OrderMessage.getDefaultInstance();
      }

      @java.lang.Override
      public protos.order.Order.OrderMessage build() {
        protos.order.Order.OrderMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.order.Order.OrderMessage buildPartial() {
        protos.order.Order.OrderMessage result = new protos.order.Order.OrderMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.manufacturer_ = manufacturer_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.product_ = product_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.quantity_ = quantity_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.willingPrice_ = willingPrice_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.order.Order.OrderMessage) {
          return mergeFrom((protos.order.Order.OrderMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.order.Order.OrderMessage other) {
        if (other == protos.order.Order.OrderMessage.getDefaultInstance()) return this;
        if (other.hasManufacturer()) {
          bitField0_ |= 0x00000001;
          manufacturer_ = other.manufacturer_;
          onChanged();
        }
        if (other.hasProduct()) {
          bitField0_ |= 0x00000002;
          product_ = other.product_;
          onChanged();
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        if (other.hasWillingPrice()) {
          setWillingPrice(other.getWillingPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasManufacturer()) {
          return false;
        }
        if (!hasProduct()) {
          return false;
        }
        if (!hasQuantity()) {
          return false;
        }
        if (!hasWillingPrice()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.order.Order.OrderMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.order.Order.OrderMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object manufacturer_ = "";
      /**
       * <code>required string manufacturer = 1;</code>
       * @return Whether the manufacturer field is set.
       */
      public boolean hasManufacturer() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string manufacturer = 1;</code>
       * @return The manufacturer.
       */
      public java.lang.String getManufacturer() {
        java.lang.Object ref = manufacturer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            manufacturer_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string manufacturer = 1;</code>
       * @return The bytes for manufacturer.
       */
      public com.google.protobuf.ByteString
          getManufacturerBytes() {
        java.lang.Object ref = manufacturer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          manufacturer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string manufacturer = 1;</code>
       * @param value The manufacturer to set.
       * @return This builder for chaining.
       */
      public Builder setManufacturer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        manufacturer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string manufacturer = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearManufacturer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        manufacturer_ = getDefaultInstance().getManufacturer();
        onChanged();
        return this;
      }
      /**
       * <code>required string manufacturer = 1;</code>
       * @param value The bytes for manufacturer to set.
       * @return This builder for chaining.
       */
      public Builder setManufacturerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        manufacturer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object product_ = "";
      /**
       * <code>required string product = 2;</code>
       * @return Whether the product field is set.
       */
      public boolean hasProduct() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string product = 2;</code>
       * @return The product.
       */
      public java.lang.String getProduct() {
        java.lang.Object ref = product_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            product_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string product = 2;</code>
       * @return The bytes for product.
       */
      public com.google.protobuf.ByteString
          getProductBytes() {
        java.lang.Object ref = product_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          product_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string product = 2;</code>
       * @param value The product to set.
       * @return This builder for chaining.
       */
      public Builder setProduct(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        product_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string product = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProduct() {
        bitField0_ = (bitField0_ & ~0x00000002);
        product_ = getDefaultInstance().getProduct();
        onChanged();
        return this;
      }
      /**
       * <code>required string product = 2;</code>
       * @param value The bytes for product to set.
       * @return This builder for chaining.
       */
      public Builder setProductBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        product_ = value;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>required int32 quantity = 3;</code>
       * @return Whether the quantity field is set.
       */
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 quantity = 3;</code>
       * @return The quantity.
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>required int32 quantity = 3;</code>
       * @param value The quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantity(int value) {
        bitField0_ |= 0x00000004;
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 quantity = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000004);
        quantity_ = 0;
        onChanged();
        return this;
      }

      private int willingPrice_ ;
      /**
       * <code>required int32 willing_price = 4;</code>
       * @return Whether the willingPrice field is set.
       */
      public boolean hasWillingPrice() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int32 willing_price = 4;</code>
       * @return The willingPrice.
       */
      public int getWillingPrice() {
        return willingPrice_;
      }
      /**
       * <code>required int32 willing_price = 4;</code>
       * @param value The willingPrice to set.
       * @return This builder for chaining.
       */
      public Builder setWillingPrice(int value) {
        bitField0_ |= 0x00000008;
        willingPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 willing_price = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWillingPrice() {
        bitField0_ = (bitField0_ & ~0x00000008);
        willingPrice_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:order.OrderMessage)
    }

    // @@protoc_insertion_point(class_scope:order.OrderMessage)
    private static final protos.order.Order.OrderMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.order.Order.OrderMessage();
    }

    public static protos.order.Order.OrderMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<OrderMessage>
        PARSER = new com.google.protobuf.AbstractParser<OrderMessage>() {
      @java.lang.Override
      public OrderMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.order.Order.OrderMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_OrderMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_OrderMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\022\005order\"^\n\014OrderMessage\022\024\n\014" +
      "manufacturer\030\001 \002(\t\022\017\n\007product\030\002 \002(\t\022\020\n\010q" +
      "uantity\030\003 \002(\005\022\025\n\rwilling_price\030\004 \002(\005B\016\n\014" +
      "protos.order"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_order_OrderMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_order_OrderMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_OrderMessage_descriptor,
        new java.lang.String[] { "Manufacturer", "Product", "Quantity", "WillingPrice", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
