%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.11.0

-ifndef(teste).
-define(teste, true).

-define(teste_gpb_version, "4.11.0").

-ifndef('PERSON_PB_H').
-define('PERSON_PB_H', true).
-record('Person',
        {name                   :: iodata(),        % = 1
         id                     :: integer(),       % = 2, 32 bits
         email                  :: iodata()         % = 3
        }).
-endif.

-endif.
