%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.11.0

-ifndef(autresponse).
-define(autresponse, true).

-define(autresponse_gpb_version, "4.11.0").

-ifndef('AUTRESPONSE_PB_H').
-define('AUTRESPONSE_PB_H', true).
-record('AutResponse',
        {autResType             :: 'USER_NOT_EXISTS' | 'WRONG_PW' | 'LOGGED_IN' | 'USER_EXISTS' | 'USER_CREATED' | integer() % = 1, enum AutResponseType
        }).
-endif.

-endif.
