%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.11.0

-ifndef(fesrequest).
-define(fesrequest, true).

-define(fesrequest_gpb_version, "4.11.0").

-ifndef('FESREQUEST_PB_H').
-define('FESREQUEST_PB_H', true).
-record('FESRequest',
        {atype                  :: 'LOGIN' | 'CREATE' | integer(), % = 1, enum FESRequest.AType
         login                  :: iodata(),        % = 2
         pw                     :: iodata()         % = 3
        }).
-endif.

-endif.
