// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authentication.proto

package protos.authentication;

public final class Authentication {
  private Authentication() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code authentication.ClientType}
   */
  public enum ClientType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>IMPORTER = 0;</code>
     */
    IMPORTER(0),
    /**
     * <code>MANUFACTURER = 1;</code>
     */
    MANUFACTURER(1),
    ;

    /**
     * <code>IMPORTER = 0;</code>
     */
    public static final int IMPORTER_VALUE = 0;
    /**
     * <code>MANUFACTURER = 1;</code>
     */
    public static final int MANUFACTURER_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ClientType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ClientType forNumber(int value) {
      switch (value) {
        case 0: return IMPORTER;
        case 1: return MANUFACTURER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ClientType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ClientType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ClientType>() {
            public ClientType findValueByNumber(int number) {
              return ClientType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protos.authentication.Authentication.getDescriptor().getEnumTypes().get(0);
    }

    private static final ClientType[] VALUES = values();

    public static ClientType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ClientType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:authentication.ClientType)
  }

  /**
   * Protobuf enum {@code authentication.AuthenticationRequestType}
   */
  public enum AuthenticationRequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REGISTER = 0;</code>
     */
    REGISTER(0),
    /**
     * <code>LOGIN = 1;</code>
     */
    LOGIN(1),
    /**
     * <code>LOGOUT = 2;</code>
     */
    LOGOUT(2),
    ;

    /**
     * <code>REGISTER = 0;</code>
     */
    public static final int REGISTER_VALUE = 0;
    /**
     * <code>LOGIN = 1;</code>
     */
    public static final int LOGIN_VALUE = 1;
    /**
     * <code>LOGOUT = 2;</code>
     */
    public static final int LOGOUT_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AuthenticationRequestType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AuthenticationRequestType forNumber(int value) {
      switch (value) {
        case 0: return REGISTER;
        case 1: return LOGIN;
        case 2: return LOGOUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AuthenticationRequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AuthenticationRequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AuthenticationRequestType>() {
            public AuthenticationRequestType findValueByNumber(int number) {
              return AuthenticationRequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protos.authentication.Authentication.getDescriptor().getEnumTypes().get(1);
    }

    private static final AuthenticationRequestType[] VALUES = values();

    public static AuthenticationRequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AuthenticationRequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:authentication.AuthenticationRequestType)
  }

  public interface AuthenticationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:authentication.AuthenticationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .authentication.AuthenticationRequestType authType = 1;</code>
     * @return Whether the authType field is set.
     */
    boolean hasAuthType();
    /**
     * <code>required .authentication.AuthenticationRequestType authType = 1;</code>
     * @return The authType.
     */
    protos.authentication.Authentication.AuthenticationRequestType getAuthType();

    /**
     * <code>required .authentication.ClientType clientType = 2;</code>
     * @return Whether the clientType field is set.
     */
    boolean hasClientType();
    /**
     * <code>required .authentication.ClientType clientType = 2;</code>
     * @return The clientType.
     */
    protos.authentication.Authentication.ClientType getClientType();

    /**
     * <code>required string username = 3;</code>
     * @return Whether the username field is set.
     */
    boolean hasUsername();
    /**
     * <code>required string username = 3;</code>
     * @return The username.
     */
    java.lang.String getUsername();
    /**
     * <code>required string username = 3;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>required string password = 4;</code>
     * @return Whether the password field is set.
     */
    boolean hasPassword();
    /**
     * <code>required string password = 4;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 4;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code authentication.AuthenticationRequest}
   */
  public  static final class AuthenticationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:authentication.AuthenticationRequest)
      AuthenticationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthenticationRequest.newBuilder() to construct.
    private AuthenticationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthenticationRequest() {
      authType_ = 0;
      clientType_ = 0;
      username_ = "";
      password_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AuthenticationRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuthenticationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              protos.authentication.Authentication.AuthenticationRequestType value = protos.authentication.Authentication.AuthenticationRequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                authType_ = rawValue;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              protos.authentication.Authentication.ClientType value = protos.authentication.Authentication.ClientType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                clientType_ = rawValue;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              username_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              password_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.authentication.Authentication.internal_static_authentication_AuthenticationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.authentication.Authentication.internal_static_authentication_AuthenticationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.authentication.Authentication.AuthenticationRequest.class, protos.authentication.Authentication.AuthenticationRequest.Builder.class);
    }

    private int bitField0_;
    public static final int AUTHTYPE_FIELD_NUMBER = 1;
    private int authType_;
    /**
     * <code>required .authentication.AuthenticationRequestType authType = 1;</code>
     * @return Whether the authType field is set.
     */
    public boolean hasAuthType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .authentication.AuthenticationRequestType authType = 1;</code>
     * @return The authType.
     */
    public protos.authentication.Authentication.AuthenticationRequestType getAuthType() {
      @SuppressWarnings("deprecation")
      protos.authentication.Authentication.AuthenticationRequestType result = protos.authentication.Authentication.AuthenticationRequestType.valueOf(authType_);
      return result == null ? protos.authentication.Authentication.AuthenticationRequestType.REGISTER : result;
    }

    public static final int CLIENTTYPE_FIELD_NUMBER = 2;
    private int clientType_;
    /**
     * <code>required .authentication.ClientType clientType = 2;</code>
     * @return Whether the clientType field is set.
     */
    public boolean hasClientType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .authentication.ClientType clientType = 2;</code>
     * @return The clientType.
     */
    public protos.authentication.Authentication.ClientType getClientType() {
      @SuppressWarnings("deprecation")
      protos.authentication.Authentication.ClientType result = protos.authentication.Authentication.ClientType.valueOf(clientType_);
      return result == null ? protos.authentication.Authentication.ClientType.IMPORTER : result;
    }

    public static final int USERNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object username_;
    /**
     * <code>required string username = 3;</code>
     * @return Whether the username field is set.
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string username = 3;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string username = 3;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 4;
    private volatile java.lang.Object password_;
    /**
     * <code>required string password = 4;</code>
     * @return Whether the password field is set.
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string password = 4;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 4;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAuthType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, authType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, clientType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, username_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, password_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, authType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, clientType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, username_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.authentication.Authentication.AuthenticationRequest)) {
        return super.equals(obj);
      }
      protos.authentication.Authentication.AuthenticationRequest other = (protos.authentication.Authentication.AuthenticationRequest) obj;

      if (hasAuthType() != other.hasAuthType()) return false;
      if (hasAuthType()) {
        if (authType_ != other.authType_) return false;
      }
      if (hasClientType() != other.hasClientType()) return false;
      if (hasClientType()) {
        if (clientType_ != other.clientType_) return false;
      }
      if (hasUsername() != other.hasUsername()) return false;
      if (hasUsername()) {
        if (!getUsername()
            .equals(other.getUsername())) return false;
      }
      if (hasPassword() != other.hasPassword()) return false;
      if (hasPassword()) {
        if (!getPassword()
            .equals(other.getPassword())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAuthType()) {
        hash = (37 * hash) + AUTHTYPE_FIELD_NUMBER;
        hash = (53 * hash) + authType_;
      }
      if (hasClientType()) {
        hash = (37 * hash) + CLIENTTYPE_FIELD_NUMBER;
        hash = (53 * hash) + clientType_;
      }
      if (hasUsername()) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUsername().hashCode();
      }
      if (hasPassword()) {
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.authentication.Authentication.AuthenticationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.authentication.Authentication.AuthenticationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.authentication.Authentication.AuthenticationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.authentication.Authentication.AuthenticationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.authentication.Authentication.AuthenticationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.authentication.Authentication.AuthenticationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.authentication.Authentication.AuthenticationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.authentication.Authentication.AuthenticationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.authentication.Authentication.AuthenticationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.authentication.Authentication.AuthenticationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.authentication.Authentication.AuthenticationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.authentication.Authentication.AuthenticationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.authentication.Authentication.AuthenticationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code authentication.AuthenticationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:authentication.AuthenticationRequest)
        protos.authentication.Authentication.AuthenticationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.authentication.Authentication.internal_static_authentication_AuthenticationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.authentication.Authentication.internal_static_authentication_AuthenticationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.authentication.Authentication.AuthenticationRequest.class, protos.authentication.Authentication.AuthenticationRequest.Builder.class);
      }

      // Construct using protos.authentication.Authentication.AuthenticationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        authType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        clientType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.authentication.Authentication.internal_static_authentication_AuthenticationRequest_descriptor;
      }

      @java.lang.Override
      public protos.authentication.Authentication.AuthenticationRequest getDefaultInstanceForType() {
        return protos.authentication.Authentication.AuthenticationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public protos.authentication.Authentication.AuthenticationRequest build() {
        protos.authentication.Authentication.AuthenticationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.authentication.Authentication.AuthenticationRequest buildPartial() {
        protos.authentication.Authentication.AuthenticationRequest result = new protos.authentication.Authentication.AuthenticationRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.authType_ = authType_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientType_ = clientType_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.authentication.Authentication.AuthenticationRequest) {
          return mergeFrom((protos.authentication.Authentication.AuthenticationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.authentication.Authentication.AuthenticationRequest other) {
        if (other == protos.authentication.Authentication.AuthenticationRequest.getDefaultInstance()) return this;
        if (other.hasAuthType()) {
          setAuthType(other.getAuthType());
        }
        if (other.hasClientType()) {
          setClientType(other.getClientType());
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000004;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000008;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAuthType()) {
          return false;
        }
        if (!hasClientType()) {
          return false;
        }
        if (!hasUsername()) {
          return false;
        }
        if (!hasPassword()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.authentication.Authentication.AuthenticationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.authentication.Authentication.AuthenticationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int authType_ = 0;
      /**
       * <code>required .authentication.AuthenticationRequestType authType = 1;</code>
       * @return Whether the authType field is set.
       */
      public boolean hasAuthType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .authentication.AuthenticationRequestType authType = 1;</code>
       * @return The authType.
       */
      public protos.authentication.Authentication.AuthenticationRequestType getAuthType() {
        @SuppressWarnings("deprecation")
        protos.authentication.Authentication.AuthenticationRequestType result = protos.authentication.Authentication.AuthenticationRequestType.valueOf(authType_);
        return result == null ? protos.authentication.Authentication.AuthenticationRequestType.REGISTER : result;
      }
      /**
       * <code>required .authentication.AuthenticationRequestType authType = 1;</code>
       * @param value The authType to set.
       * @return This builder for chaining.
       */
      public Builder setAuthType(protos.authentication.Authentication.AuthenticationRequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        authType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .authentication.AuthenticationRequestType authType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        authType_ = 0;
        onChanged();
        return this;
      }

      private int clientType_ = 0;
      /**
       * <code>required .authentication.ClientType clientType = 2;</code>
       * @return Whether the clientType field is set.
       */
      public boolean hasClientType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required .authentication.ClientType clientType = 2;</code>
       * @return The clientType.
       */
      public protos.authentication.Authentication.ClientType getClientType() {
        @SuppressWarnings("deprecation")
        protos.authentication.Authentication.ClientType result = protos.authentication.Authentication.ClientType.valueOf(clientType_);
        return result == null ? protos.authentication.Authentication.ClientType.IMPORTER : result;
      }
      /**
       * <code>required .authentication.ClientType clientType = 2;</code>
       * @param value The clientType to set.
       * @return This builder for chaining.
       */
      public Builder setClientType(protos.authentication.Authentication.ClientType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        clientType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .authentication.ClientType clientType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>required string username = 3;</code>
       * @return Whether the username field is set.
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string username = 3;</code>
       * @return The username.
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string username = 3;</code>
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string username = 3;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000004);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 3;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 4;</code>
       * @return Whether the password field is set.
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string password = 4;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 4;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 4;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000008);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 4;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        password_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:authentication.AuthenticationRequest)
    }

    // @@protoc_insertion_point(class_scope:authentication.AuthenticationRequest)
    private static final protos.authentication.Authentication.AuthenticationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.authentication.Authentication.AuthenticationRequest();
    }

    public static protos.authentication.Authentication.AuthenticationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AuthenticationRequest>
        PARSER = new com.google.protobuf.AbstractParser<AuthenticationRequest>() {
      @java.lang.Override
      public AuthenticationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthenticationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuthenticationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthenticationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.authentication.Authentication.AuthenticationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authentication_AuthenticationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authentication_AuthenticationRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024authentication.proto\022\016authentication\"\250" +
      "\001\n\025AuthenticationRequest\022;\n\010authType\030\001 \002" +
      "(\0162).authentication.AuthenticationReques" +
      "tType\022.\n\nclientType\030\002 \002(\0162\032.authenticati" +
      "on.ClientType\022\020\n\010username\030\003 \002(\t\022\020\n\010passw" +
      "ord\030\004 \002(\t*,\n\nClientType\022\014\n\010IMPORTER\020\000\022\020\n" +
      "\014MANUFACTURER\020\001*@\n\031AuthenticationRequest" +
      "Type\022\014\n\010REGISTER\020\000\022\t\n\005LOGIN\020\001\022\n\n\006LOGOUT\020" +
      "\002B\027\n\025protos.authentication"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_authentication_AuthenticationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_authentication_AuthenticationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authentication_AuthenticationRequest_descriptor,
        new java.lang.String[] { "AuthType", "ClientType", "Username", "Password", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
