// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autresponse.proto

package protos.authentication;

public final class AuthenticationReply {
  private AuthenticationReply() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code authentication.AutResponseType}
   */
  public enum AutResponseType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * referentes a login
     * </pre>
     *
     * <code>USER_NOT_EXISTS = 1;</code>
     */
    USER_NOT_EXISTS(1),
    /**
     * <code>WRONG_PW = 2;</code>
     */
    WRONG_PW(2),
    /**
     * <code>LOGGED_IN = 3;</code>
     */
    LOGGED_IN(3),
    /**
     * <pre>
     * referentes a criacao de conta
     * </pre>
     *
     * <code>USER_EXISTS = 4;</code>
     */
    USER_EXISTS(4),
    /**
     * <code>USER_CREATED = 5;</code>
     */
    USER_CREATED(5),
    ;

    /**
     * <pre>
     * referentes a login
     * </pre>
     *
     * <code>USER_NOT_EXISTS = 1;</code>
     */
    public static final int USER_NOT_EXISTS_VALUE = 1;
    /**
     * <code>WRONG_PW = 2;</code>
     */
    public static final int WRONG_PW_VALUE = 2;
    /**
     * <code>LOGGED_IN = 3;</code>
     */
    public static final int LOGGED_IN_VALUE = 3;
    /**
     * <pre>
     * referentes a criacao de conta
     * </pre>
     *
     * <code>USER_EXISTS = 4;</code>
     */
    public static final int USER_EXISTS_VALUE = 4;
    /**
     * <code>USER_CREATED = 5;</code>
     */
    public static final int USER_CREATED_VALUE = 5;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AutResponseType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AutResponseType forNumber(int value) {
      switch (value) {
        case 1: return USER_NOT_EXISTS;
        case 2: return WRONG_PW;
        case 3: return LOGGED_IN;
        case 4: return USER_EXISTS;
        case 5: return USER_CREATED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AutResponseType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AutResponseType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AutResponseType>() {
            public AutResponseType findValueByNumber(int number) {
              return AutResponseType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protos.authentication.AuthenticationReply.getDescriptor().getEnumTypes().get(0);
    }

    private static final AutResponseType[] VALUES = values();

    public static AutResponseType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AutResponseType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:authentication.AutResponseType)
  }

  public interface AutResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:authentication.AutResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .authentication.AutResponseType autResType = 1;</code>
     * @return Whether the autResType field is set.
     */
    boolean hasAutResType();
    /**
     * <code>required .authentication.AutResponseType autResType = 1;</code>
     * @return The autResType.
     */
    protos.authentication.AuthenticationReply.AutResponseType getAutResType();
  }
  /**
   * Protobuf type {@code authentication.AutResponse}
   */
  public  static final class AutResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:authentication.AutResponse)
      AutResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AutResponse.newBuilder() to construct.
    private AutResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AutResponse() {
      autResType_ = 1;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AutResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AutResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              protos.authentication.AuthenticationReply.AutResponseType value = protos.authentication.AuthenticationReply.AutResponseType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                autResType_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.authentication.AuthenticationReply.internal_static_authentication_AutResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.authentication.AuthenticationReply.internal_static_authentication_AutResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.authentication.AuthenticationReply.AutResponse.class, protos.authentication.AuthenticationReply.AutResponse.Builder.class);
    }

    private int bitField0_;
    public static final int AUTRESTYPE_FIELD_NUMBER = 1;
    private int autResType_;
    /**
     * <code>required .authentication.AutResponseType autResType = 1;</code>
     * @return Whether the autResType field is set.
     */
    public boolean hasAutResType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .authentication.AutResponseType autResType = 1;</code>
     * @return The autResType.
     */
    public protos.authentication.AuthenticationReply.AutResponseType getAutResType() {
      @SuppressWarnings("deprecation")
      protos.authentication.AuthenticationReply.AutResponseType result = protos.authentication.AuthenticationReply.AutResponseType.valueOf(autResType_);
      return result == null ? protos.authentication.AuthenticationReply.AutResponseType.USER_NOT_EXISTS : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAutResType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, autResType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, autResType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.authentication.AuthenticationReply.AutResponse)) {
        return super.equals(obj);
      }
      protos.authentication.AuthenticationReply.AutResponse other = (protos.authentication.AuthenticationReply.AutResponse) obj;

      if (hasAutResType() != other.hasAutResType()) return false;
      if (hasAutResType()) {
        if (autResType_ != other.autResType_) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAutResType()) {
        hash = (37 * hash) + AUTRESTYPE_FIELD_NUMBER;
        hash = (53 * hash) + autResType_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.authentication.AuthenticationReply.AutResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.authentication.AuthenticationReply.AutResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.authentication.AuthenticationReply.AutResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.authentication.AuthenticationReply.AutResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.authentication.AuthenticationReply.AutResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.authentication.AuthenticationReply.AutResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.authentication.AuthenticationReply.AutResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.authentication.AuthenticationReply.AutResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.authentication.AuthenticationReply.AutResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.authentication.AuthenticationReply.AutResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.authentication.AuthenticationReply.AutResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.authentication.AuthenticationReply.AutResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.authentication.AuthenticationReply.AutResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code authentication.AutResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:authentication.AutResponse)
        protos.authentication.AuthenticationReply.AutResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.authentication.AuthenticationReply.internal_static_authentication_AutResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.authentication.AuthenticationReply.internal_static_authentication_AutResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.authentication.AuthenticationReply.AutResponse.class, protos.authentication.AuthenticationReply.AutResponse.Builder.class);
      }

      // Construct using protos.authentication.AuthenticationReply.AutResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        autResType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.authentication.AuthenticationReply.internal_static_authentication_AutResponse_descriptor;
      }

      @java.lang.Override
      public protos.authentication.AuthenticationReply.AutResponse getDefaultInstanceForType() {
        return protos.authentication.AuthenticationReply.AutResponse.getDefaultInstance();
      }

      @java.lang.Override
      public protos.authentication.AuthenticationReply.AutResponse build() {
        protos.authentication.AuthenticationReply.AutResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.authentication.AuthenticationReply.AutResponse buildPartial() {
        protos.authentication.AuthenticationReply.AutResponse result = new protos.authentication.AuthenticationReply.AutResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.autResType_ = autResType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.authentication.AuthenticationReply.AutResponse) {
          return mergeFrom((protos.authentication.AuthenticationReply.AutResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.authentication.AuthenticationReply.AutResponse other) {
        if (other == protos.authentication.AuthenticationReply.AutResponse.getDefaultInstance()) return this;
        if (other.hasAutResType()) {
          setAutResType(other.getAutResType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAutResType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.authentication.AuthenticationReply.AutResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.authentication.AuthenticationReply.AutResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int autResType_ = 1;
      /**
       * <code>required .authentication.AutResponseType autResType = 1;</code>
       * @return Whether the autResType field is set.
       */
      public boolean hasAutResType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .authentication.AutResponseType autResType = 1;</code>
       * @return The autResType.
       */
      public protos.authentication.AuthenticationReply.AutResponseType getAutResType() {
        @SuppressWarnings("deprecation")
        protos.authentication.AuthenticationReply.AutResponseType result = protos.authentication.AuthenticationReply.AutResponseType.valueOf(autResType_);
        return result == null ? protos.authentication.AuthenticationReply.AutResponseType.USER_NOT_EXISTS : result;
      }
      /**
       * <code>required .authentication.AutResponseType autResType = 1;</code>
       * @param value The autResType to set.
       * @return This builder for chaining.
       */
      public Builder setAutResType(protos.authentication.AuthenticationReply.AutResponseType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        autResType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .authentication.AutResponseType autResType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAutResType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        autResType_ = 1;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:authentication.AutResponse)
    }

    // @@protoc_insertion_point(class_scope:authentication.AutResponse)
    private static final protos.authentication.AuthenticationReply.AutResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.authentication.AuthenticationReply.AutResponse();
    }

    public static protos.authentication.AuthenticationReply.AutResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AutResponse>
        PARSER = new com.google.protobuf.AbstractParser<AutResponse>() {
      @java.lang.Override
      public AutResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AutResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AutResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AutResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.authentication.AuthenticationReply.AutResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authentication_AutResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authentication_AutResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021autresponse.proto\022\016authentication\"B\n\013A" +
      "utResponse\0223\n\nautResType\030\001 \002(\0162\037.authent" +
      "ication.AutResponseType*f\n\017AutResponseTy" +
      "pe\022\023\n\017USER_NOT_EXISTS\020\001\022\014\n\010WRONG_PW\020\002\022\r\n" +
      "\tLOGGED_IN\020\003\022\017\n\013USER_EXISTS\020\004\022\020\n\014USER_CR" +
      "EATED\020\005B,\n\025protos.authenticationB\023Authen" +
      "ticationReply"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_authentication_AutResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_authentication_AutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authentication_AutResponse_descriptor,
        new java.lang.String[] { "AutResType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
